my.secretkey: R28K42ZEJ8LWRHU5
my.salt: 636eac2534bcfcb0

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
        namespace: 6668a16f-cc7d-4245-9f11-3e7c55868347
  application:
    name: rbac-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bosstrain?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 957ilovemyfamily


logging:
  level:
    root: warn
    com.boss: debug