server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bosstrain?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 957ilovemyfamily
  redis:
    password: 123456
  application:
    name: nacos-getway
  cloud:
    gateway:
      routes:
        - id: login-service        #路由名，保证唯一
          #          uri: lb://nacos-provider        #推荐使用，使用动态路由。lb：loadBanlance负载均衡,但是需要注册为服务
          uri: http://localhost:8001       #不推荐使用，写死了端口，不能动态改变不需要注册为服务
          predicates:                      #断言。满足条件则运行，有多种参数：path、after、before、between。
            - Path=/api/login
#            - After=2020-08-02T10:55:30.809+08:00[GMT+08:00]   #可以通过ZonedDateTime.now()获取
        - id: rbac-service
#          uri: lb://nacos-consumer
          uri: http://localhost:8002
          predicates:
            - Path=/api/**