server:
  port: 8002

spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
  application:
    name: rbac-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bosstrain?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 957ilovemyfamily